import type { ContentPage } from "./types";

/**
 * "The State of AI Agent Identity, 2026" — desk review, researched 2026-09-23.
 * Every date, number and status below comes from a source fetched on that date and
 * cited inline; every external URL in the body also appears in `sources`.
 */
export const REPORT: ContentPage = {
  slug: "state-of-agent-identity",
  title: "The State of AI Agent Identity 2026: Standards & Gaps",
  description:
    "A sourced 2026 review of AI agent identity: IETF, W3C, A2A and MCP work, enterprise and payments approaches, EU AI Act Article 50, and the problems still open.",
  h1: "The State of AI Agent Identity, 2026",
  keywords: [
    "AI agent identity",
    "state of agent identity 2026",
    "agent authentication standards",
    "Web Bot Auth",
    "HTTP Message Signatures",
    "Agent Name Service",
    "A2A Agent Card",
    "MCP authorization",
    "know your agent",
    "EU AI Act Article 50",
    "agent delegation",
    "non-human identity",
  ],
  lead: [
    "Software that acts on its own now calls businesses, browses websites, buys things and talks to other software. Each of those interactions raises the same question on the receiving end: which agent is this, who runs it, and can that be checked without taking the agent's word for it? This report is a desk review of how standards bodies, vendors and regulators were answering that question as of September 2026.",
    "It follows one rule: every number, date, launch and quote comes from a source we fetched and cite inline. Where a figure is a vendor's own claim, a forecast or a survey, it is labelled that way. Where we could not find a primary source, we left the claim out. The final sections describe where AgenID sits in this landscape, including what it does not do yet, and how to report a correction.",
  ],
  sections: [
    {
      heading: "Executive summary",
      body: [
        "The short version: agent identity moved from research papers to shipping products in 2025 and 2026, but the work split along several lines that do not yet connect. Request signing, naming, enterprise directories, payment networks and agent-to-agent protocols each identify something slightly different, and none of them on its own tells a stranger who authorized an agent to act. Which agent is acting is not the same question as what it is allowed to do, and most of the unresolved work sits in the gap between the two.",
      ],
      bullets: [
        "Request-level bot and agent authentication is converging on HTTP Message Signatures ([RFC 9421](https://www.rfc-editor.org/rfc/rfc9421.html), February 2024). The IETF now has an active Web Bot Auth working group, and its first working-group draft is dated September 1, 2026 ([IETF datatracker](https://datatracker.ietf.org/doc/draft-ietf-webbotauth-httpsig-protocol/)).",
        "Agent naming is being proposed at the IETF as individual submissions only: the Agent Name Service v2 draft, revision 01, dated April 13, 2026, lists a GoDaddy author and is not a working-group document ([IETF datatracker](https://datatracker.ietf.org/doc/draft-narajala-courtney-ansv2/)).",
        "Agent-to-agent and agent-to-tool protocols moved to neutral foundations: A2A to the Linux Foundation on June 23, 2025 ([Linux Foundation](https://www.linuxfoundation.org/press/linux-foundation-launches-the-agent2agent-protocol-project-to-enable-secure-intelligent-communication-between-ai-agents)) and MCP to the new Agentic AI Foundation on December 9, 2025 ([Linux Foundation](https://www.linuxfoundation.org/press/linux-foundation-announces-the-formation-of-the-agentic-ai-foundation)). MCP's own specification still states that authorization is optional ([MCP specification](https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization)).",
        "Enterprise identity vendors now treat agents as their own identity type: Microsoft announced Entra Agent ID on May 19, 2025 ([Microsoft Security blog](https://www.microsoft.com/en-us/security/blog/2025/05/19/microsoft-extends-zero-trust-to-secure-the-agentic-workforce/)), and Auth0 announced Auth0 for AI Agents on September 25, 2025 ([Auth0](https://auth0.com/blog/announcing-auth0-for-ai-agents-powering-the-future-of-ai-securely/)).",
        "Payment networks each built their own agent trust layer in 2025: Mastercard Agent Pay (April 29), Google's AP2 (September 16) and Visa's Trusted Agent Protocol (October 14), the last built on HTTP Message Signatures and aligned with Web Bot Auth ([Visa](https://usa.visa.com/about-visa/newsroom/press-releases.releaseId.21716.html)).",
        "Regulation arrived on disclosure, not identity: the EU AI Act's Article 50 transparency rules apply from August 2, 2026, according to the European Commission ([European Commission](https://digital-strategy.ec.europa.eu/en/factpages/quick-facts-transparency-rules-ai-systems)). They require telling people they are dealing with an AI system; they do not define a portable agent identifier.",
        "The US federal standards body framed the open problems as questions rather than answers: NIST's NCCoE concept paper of February 5, 2026 asks how to handle key revocation, delegation for on-behalf-of scenarios, and binding agent identity to human identity ([NIST CSRC](https://csrc.nist.gov/pubs/other/2026/02/05/accelerating-the-adoption-of-software-and-ai-agent/ipd)).",
      ],
    },
    {
      heading: "Why agent identity became a question in 2025–2026",
      body: [
        "The first signal is the plumbing. Anthropic introduced the Model Context Protocol on November 25, 2024 as \"an open standard for connecting AI assistants to the systems where data lives\" ([Anthropic](https://www.anthropic.com/news/model-context-protocol)). By the time MCP was contributed to the Linux Foundation's new Agentic AI Foundation on December 9, 2025, the foundation's announcement stated there were \"more than 10,000 published MCP servers\" ([Linux Foundation](https://www.linuxfoundation.org/press/linux-foundation-announces-the-formation-of-the-agentic-ai-foundation)). That figure is the foundation's own count, not an independent census, but it shows how many new endpoints an agent can now reach.",
        "The second signal is agent-to-agent traffic. Google launched the Agent2Agent protocol on April 9, 2025 with, in its words, \"support and contributions from more than 50 technology partners\" ([Google Developers Blog](https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/)). When the Linux Foundation took the project on at Open Source Summit North America on June 23, 2025, its release cited \"growing support from more than 100 leading technology companies\" ([Linux Foundation](https://www.linuxfoundation.org/press/linux-foundation-launches-the-agent2agent-protocol-project-to-enable-secure-intelligent-communication-between-ai-agents)). Both counts are the sponsors' own.",
        "The third signal is enterprise adoption, where the best available numbers are surveys and forecasts rather than measurements. McKinsey's \"The state of AI in 2026\" survey, with 1,719 respondents fielded May 4 to June 8, 2026, reports that 40 percent of respondents from organizations with more than $1 billion in annual revenue say they are scaling AI agents, up from 27 percent a year earlier, while the share at smaller organizations stayed at 22 percent ([McKinsey](https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai)). Gartner, in an August 26, 2025 forecast, predicted that 40 percent of enterprise applications will be integrated with task-specific AI agents by the end of 2026, up from less than 5 percent at the time of the release ([Gartner](https://www.gartner.com/en/newsroom/press-releases/2025-08-26-gartner-predicts-40-percent-of-enterprise-apps-will-feature-task-specific-ai-agents-by-2026-up-from-less-than-5-percent-in-2025)). That is a prediction, not an observed figure.",
        "The fourth signal is the web itself. Cloudflare argued on May 15, 2025 that user-agent strings and IP ranges were too weak to tell bots and agents apart, and proposed that \"developers of bots and agents cryptographically sign requests originating from their service\" ([Cloudflare](https://blog.cloudflare.com/web-bot-auth/)). By August 28, 2025 it had named an initial cohort of \"signed agents\" that included OpenAI's ChatGPT agent, Block's Goose, Browserbase and Anchor Browser ([Cloudflare](https://blog.cloudflare.com/signed-agents/)).",
        "Researchers had framed the problem earlier. A June 2024 paper proposed identifiers for individual AI system instances, arguing that \"IDs seem most warranted in settings where AI systems could have a large impact upon the world, such as in making financial transactions or contacting real humans\" ([Chan et al., arXiv](https://arxiv.org/abs/2406.12137)). A January 2025 paper proposed extending OAuth 2.0 and OpenID Connect for \"authenticated, authorized, and auditable delegation of authority to AI agents\" ([South et al., arXiv](https://arxiv.org/abs/2501.09674)). The OpenID Foundation's October 7, 2025 whitepaper concluded that existing standards can secure many current agent use cases but warned that \"the window for establishing robust, interoperable standards is now, before proprietary solutions fragment the ecosystem\" ([OpenID Foundation](https://openid.net/new-whitepaper-tackles-ai-agent-identity-challenges/)).",
      ],
    },
    {
      heading: "The standards landscape",
      body: [
        "Standards work is spread across at least five venues. They do not all identify the same thing: some identify a request, some a server, some a named service, some a credential holder. The table records each initiative's status as its own publisher states it on the date of research; the citations follow in the paragraphs below.",
        "HTTP Message Signatures. [RFC 9421](https://www.rfc-editor.org/rfc/rfc9421.html), published February 2024 on the Standards Track, defines how to sign selected components of an HTTP message so the signature survives intermediaries. It is the base layer most request-signing proposals for agents build on, including Web Bot Auth and Visa's Trusted Agent Protocol.",
        "Web Bot Auth. The IETF Web Bot Auth working group is active; its charter covers \"cryptographically authenticating automated clients and providing additional information about their operators to Web sites\" and lists search crawlers, archivers, link checkers and AI training crawlers as in scope ([IETF webbotauth charter](https://datatracker.ietf.org/wg/webbotauth/about/)). The earlier individual drafts were replaced by the working-group draft draft-ietf-webbotauth-httpsig-protocol-00, dated September 1, 2026, which defines a Signature-Agent header for key discovery, a JWKS-based key directory and a well-known URI to serve it ([IETF datatracker](https://datatracker.ietf.org/doc/draft-ietf-webbotauth-httpsig-protocol/)). Cloudflare announced on July 1, 2025 that it validates these signatures at its edge as part of its Verified Bots program ([Cloudflare](https://blog.cloudflare.com/verified-bots-with-cryptography/)).",
        "Agent Name Service. The first ANS draft (draft-narajala-ans-00, May 16, 2025) proposed a DNS-based directory for agent discovery using PKI certificates and is now expired ([IETF datatracker](https://datatracker.ietf.org/doc/draft-narajala-ans/)). Its successor, ANS v2 (draft-narajala-courtney-ansv2-01, April 13, 2026), describes \"a domain-anchored trust layer\" that anchors each agent to a verified DNS domain, issues dual certificates and records lifecycle events in a transparency log; it is an individual submission with authors from GoDaddy, OWASP, DistributedApps.ai and Cisco ([IETF datatracker](https://datatracker.ietf.org/doc/draft-narajala-courtney-ansv2/)). Individual drafts carry no IETF endorsement.",
        "W3C Decentralized Identifiers and Verifiable Credentials. DID Core became a W3C Recommendation on July 19, 2022 and describes DIDs as identifiers that enable \"verifiable, decentralized digital identity\" without a central registry ([W3C](https://www.w3.org/TR/did-1.0/)). Verifiable Credentials Data Model 2.0 became a W3C Recommendation on May 15, 2025 ([W3C](https://www.w3.org/TR/vc-data-model-2.0/)). Neither is agent-specific, but both are general tools that agent systems reuse; Google's AP2, for example, signs its payment mandates with verifiable credentials.",
        "A2A Agent Cards. The A2A specification, at version 1.0.0 on its site, defines an Agent Card as \"a JSON metadata document published by an A2A Server, describing its identity, capabilities, skills, service endpoint, and authentication requirements\" and includes an AgentCardSignature object with canonicalization rules ([A2A specification](https://a2a-protocol.org/latest/specification/)). Cards are discovered at `/.well-known/agent-card.json` on the agent server's domain ([A2A discovery guide](https://a2a-protocol.org/latest/topics/agent-discovery/)). An Agent Card describes a server; the protocol leaves client authentication to schemes the card declares, such as OAuth 2.0, OpenID Connect or mutual TLS.",
        "MCP authorization. The current MCP specification revision (2026-07-28) provides authorization \"at the transport level\" for HTTP transports, built on the OAuth 2.1 draft, OAuth Protected Resource Metadata (RFC 9728), Resource Indicators (RFC 8707) and, newly, OAuth Client ID Metadata Documents; Dynamic Client Registration is now marked deprecated. It also states plainly: \"Authorization is OPTIONAL for MCP implementations\" ([MCP specification](https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization)). MCP authorization identifies an OAuth client acting for a resource owner; it does not give the agent a portable identity outside that authorization server.",
        "OAuth and workload identity at the IETF. The WIMSE working group (Workload Identity in Multi System Environments) is active and works on identity for software workloads across platforms; its charter does not mention AI agents ([IETF WIMSE](https://datatracker.ietf.org/wg/wimse/about/)). An individual draft proposing an on-behalf-of extension to OAuth for AI agents reached revision 02 on August 25, 2025 and has expired ([IETF datatracker](https://datatracker.ietf.org/doc/draft-oauth-ai-agents-on-behalf-of-user/)).",
        "OpenID Foundation and NIST. The OpenID Foundation's AI Identity Management Community Group published \"Identity Management for Agentic AI\" on October 7, 2025, a whitepaper rather than a specification ([OpenID Foundation](https://openid.net/new-whitepaper-tackles-ai-agent-identity-challenges/)). NIST launched an AI Agent Standards Initiative on February 17, 2026 that states it \"conducts fundamental research into agent authentication and identity infrastructure\" ([NIST](https://www.nist.gov/artificial-intelligence/ai-agent-standards-initiative)), and its NCCoE concept paper on agent identity and authorization closed its public comment period on April 2, 2026 ([NIST CSRC](https://csrc.nist.gov/pubs/other/2026/02/05/accelerating-the-adoption-of-software-and-ai-agent/ipd)).",
      ],
      table: {
        caption: "Standards initiatives touching agent identity, status as stated by each source on 2026-09-23",
        columns: ["Initiative", "Body", "What it identifies", "Status per source"],
        rows: [
          ["HTTP Message Signatures (RFC 9421)", "IETF", "The signer of an HTTP message", "Standards Track RFC, February 2024"],
          ["Web Bot Auth (draft-ietf-webbotauth-httpsig-protocol)", "IETF webbotauth WG", "The operator key behind an automated HTTP request", "Working-group draft -00, September 1, 2026"],
          ["Agent Name Service v2 (draft-narajala-courtney-ansv2)", "IETF (individual submission)", "A named agent anchored to a verified DNS domain", "Individual draft -01, April 13, 2026"],
          ["DID Core 1.0", "W3C", "Any subject, via a resolvable DID document", "W3C Recommendation, July 19, 2022"],
          ["Verifiable Credentials Data Model 2.0", "W3C", "Claims made by an issuer about a subject", "W3C Recommendation, May 15, 2025"],
          ["A2A Agent Card", "A2A project, Linux Foundation", "An A2A server: identity, skills, endpoint, auth requirements", "Specification version 1.0.0"],
          ["MCP authorization", "MCP project, Agentic AI Foundation", "An OAuth client acting for a resource owner", "Spec revision 2026-07-28; authorization optional"],
          ["WIMSE", "IETF WIMSE WG", "Software workloads across trust boundaries", "Active WG; charter does not mention AI agents"],
          ["Identity Management for Agentic AI", "OpenID Foundation AIIM CG", "Not a spec; frames the problem", "Whitepaper, October 7, 2025"],
          ["Software and AI Agent Identity and Authorization", "NIST NCCoE", "Enterprise agents; asks open questions", "Concept paper, comments closed April 2, 2026"],
        ],
      },
    },
    {
      heading: "Commercial approaches",
      body: [
        "Commercial work falls into four rough groups. They are listed here without ranking, in each owner's own terms; several of them are complementary rather than competing, because they identify different things at different layers.",
        "Enterprise identity and access management. Microsoft announced Microsoft Entra Agent ID on May 19, 2025, describing it as extending \"identity management and access capabilities to AI agents\" and assigning identities automatically to agents built in Copilot Studio and Azure AI Foundry ([Microsoft Security blog](https://www.microsoft.com/en-us/security/blog/2025/05/19/microsoft-extends-zero-trust-to-secure-the-agentic-workforce/)). Microsoft's current documentation, last updated June 15, 2026, calls agent identities \"identity accounts within Microsoft Entra ID\" and states that Agent ID \"is available for all Microsoft Entra customers\" ([Microsoft Learn](https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/what-is-agent-id)). Okta's Auth0 announced Auth0 for AI Agents on September 25, 2025 with user authentication, a Token Vault for calling third-party APIs on a user's behalf, asynchronous human approval, and fine-grained authorization for retrieval; the announcement said the product, then in developer preview, would leave preview in November 2025 ([Auth0](https://auth0.com/blog/announcing-auth0-for-ai-agents-powering-the-future-of-ai-securely/)). Both identify an agent inside one organization's directory, where the relying party is usually that same organization.",
        "Registrar and naming. GoDaddy opened public access to an ANS API and a standards site on November 20, 2025; its CTO for Product and AI described the aim as letting anyone \"name an agent, verify it cryptographically\" ([GoDaddy](https://aboutus.godaddy.net/newsroom/news-releases/press-release-details/2025/GoDaddy-advances-trusted-AI-agent-identity-with-ANS-API-and-Standards-site/default.aspx)). On December 18, 2025 it launched an ANS Marketplace with five demonstration agents and 20 agents generated from WooCommerce storefronts, plus \"ANS-verified\" badges ([GoDaddy via PR Newswire](https://www.prnewswire.com/news-releases/godaddys-new-ans-marketplace-tells-you-which-ai-agents-you-can-trust-302646360.html)). This approach ties agent identity to domain control, the same anchor web PKI uses.",
        "Payment networks. Mastercard unveiled Agent Pay on April 29, 2025, built on Mastercard Agentic Tokens, and said \"the program will require trusted AI agents to be registered and verified\" before they can pay on a user's behalf ([Mastercard](https://www.mastercard.com/us/en/news-and-trends/press/2025/april/mastercard-unveils-agent-pay-pioneering-agentic-payments-technology-to-power-commerce-in-the-age-of-ai.html)). Google announced the Agent Payments Protocol (AP2) on September 16, 2025, with \"more than 60 organizations\" collaborating; AP2 records a user's instructions as cryptographically signed Intent and Cart Mandates signed by verifiable credentials, and can run as an extension of A2A and MCP ([Google Cloud](https://cloud.google.com/blog/products/ai-machine-learning/announcing-agents-to-payments-ap2-protocol)). Visa introduced the Trusted Agent Protocol on October 14, 2025, developed with Cloudflare, built on HTTP Message Signatures and aligned with Web Bot Auth, and published on the Visa Developer Center and GitHub ([Visa](https://usa.visa.com/about-visa/newsroom/press-releases.releaseId.21716.html)). Coinbase introduced x402 on May 6, 2025, an open standard that uses the HTTP 402 status code to carry stablecoin payments inside web requests ([Coinbase](https://www.coinbase.com/developer-platform/discover/launches/x402)); as described by Coinbase, it settles a payment rather than identifying the agent that makes it. In each network scheme, the network or its issuers decide which agents are recognized.",
        "Know Your Agent vendors. Skyfire launched KYAPay on June 26, 2025, describing it as \"the Open Identity and Payments Protocol for AI agents\"; per the release, it uses signed JSON Web Tokens that carry verified agent-owner information together with authorized spending ([Skyfire via Business Wire](https://www.businesswire.com/news/home/20250626772489/en/Skyfire-Launches-Open-KYAPay-Protocol-With-Agent-Checkout)). The \"know your agent\" framing borrows from financial-services know-your-customer checks: an intermediary checks the owner, then vouches for the agent to relying parties that accept that intermediary's tokens.",
        "A pattern runs through all four groups. Each approach answers the identity question for relying parties that already trust a particular issuer: a tenant's directory, a registrar, a card network or a token vendor. That is a legitimate design, and for many deployments the right one. What none of them describes is how an unrelated party, with no account at that issuer, checks an agent's identity and re-derives the result independently.",
      ],
    },
    {
      heading: "Regulation touching agent disclosure and identity",
      body: [
        "This section is context, not legal advice. Consult counsel for how any of these rules applies to a specific deployment.",
        "EU AI Act Article 50. Article 50(1) requires providers to ensure that \"AI systems intended to interact directly with natural persons are designed and developed in such a way that the natural persons concerned are informed that they are interacting with an AI system\" ([AI Act Article 50 text](https://artificialintelligenceact.eu/article/50/)). The European Commission states that the transparency rules \"apply from 2 August 2026,\" with a grace period until December 2026 for the marking obligation on generative systems placed on the market before that date ([European Commission](https://digital-strategy.ec.europa.eu/en/factpages/quick-facts-transparency-rules-ai-systems)). The Commission also records that the AI Omnibus amending regulation entered into force on July 27, 2026, and that its main timeline changes concern high-risk systems rather than the transparency obligations ([European Commission](https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai)). Article 50 is a disclosure duty: it requires telling a person that an AI system is involved, not proving to a machine which system it is.",
        "Utah. Utah's S.B. 226 (2025 General Session), with sections effective May 7, 2025, requires a supplier using generative AI in a consumer transaction to disclose that the individual is interacting with generative AI and not a human if the individual asks with \"a clear and unambiguous request,\" and requires prominent up-front disclosure in regulated occupations when the use is a high-risk interaction ([Utah Legislature, enrolled S.B. 226](https://le.utah.gov/Session/2025/bills/enrolled/SB0226.pdf)). The bill provides a safe harbor for AI that discloses clearly at the outset and throughout.",
        "United States, voice calls. The FCC's Declaratory Ruling FCC 24-17, adopted February 2, 2024 and released February 8, 2024, confirmed that the Telephone Consumer Protection Act's \"artificial or prerecorded voice\" restrictions cover AI technologies that generate human voices, and noted that its rules already require such messages to \"provide certain identification and disclosure information for the entity responsible for initiating the call\" ([FCC](https://docs.fcc.gov/public/attachments/FCC-24-17A1.pdf)). For voice agents, that makes the identity of the responsible operator a regulatory question, not only a technical one.",
        "None of these texts defines an agent identifier, a verification level or a key format. They set obligations that an identity layer can help an operator evidence, and they leave the mechanism open. A signed self-declaration that an agent is an AI is evidence of what the operator declared; it is not a finding of compliance.",
      ],
    },
    {
      heading: "Open problems",
      body: [
        "The clearest public inventory of open problems is NIST's own list of questions. Its February 2026 concept paper asks, among other things: \"How do we handle key management for agents? Issuance, update, and revocation?\", \"How do we handle delegation of authority for 'on behalf of' scenarios?\", \"How do we bind agent identity with human identity to support 'human-in-the-loop' authorizations?\" and \"How do we ensure non-repudiation for agent actions and binding back to human authorization?\" ([NIST NCCoE concept paper](https://csrc.nist.gov/pubs/other/2026/02/05/accelerating-the-adoption-of-software-and-ai-agent/ipd)). Six problems stand out from the sources reviewed here.",
      ],
      bullets: [
        "Portability across platforms. An Entra agent identity lives in an Entra tenant, an MCP client identity lives at one authorization server, and a payment-network registration lives with that network. The OpenID Foundation's warning about proprietary fragmentation describes the risk directly ([OpenID Foundation](https://openid.net/new-whitepaper-tackles-ai-agent-identity-challenges/)). An agent that crosses organizational boundaries currently carries a different identity at each.",
        "Verification without trusting the issuer. Most commercial schemes ask the relying party to trust the issuer's answer. DIDs were designed to avoid a central registry ([W3C](https://www.w3.org/TR/did-1.0/)), and Web Bot Auth lets a server verify a signature against a published key directory ([IETF datatracker](https://datatracker.ietf.org/doc/draft-ietf-webbotauth-httpsig-protocol/)). Neither, by itself, says who the key belongs to in a way a third party can re-check.",
        "Delegation and authorization. Knowing which agent is acting says nothing about what it is allowed to do. Research proposals extend OAuth and OpenID Connect for delegated agent authority ([South et al., arXiv](https://arxiv.org/abs/2501.09674)), AP2 records user intent as signed mandates ([Google Cloud](https://cloud.google.com/blog/products/ai-machine-learning/announcing-agents-to-payments-ap2-protocol)), and an IETF on-behalf-of draft for agents expired without adoption ([IETF datatracker](https://datatracker.ietf.org/doc/draft-oauth-ai-agents-on-behalf-of-user/)). No cross-industry delegation object has emerged.",
        "Revocation propagation. NIST lists revocation as an open question for agent key management ([NIST CSRC](https://csrc.nist.gov/pubs/other/2026/02/05/accelerating-the-adoption-of-software-and-ai-agent/ipd)). When an identity lives in several places at once, a revocation at one issuer does not reach verifiers who checked a different one.",
        "Binding requests to identities. A registered identity and a live request are different objects. RFC 9421 and Web Bot Auth sign individual HTTP requests ([RFC 9421](https://www.rfc-editor.org/rfc/rfc9421.html)); a manifest or card that describes an agent does not, by itself, prove that a given request came from it.",
        "Human and organization binding. The FCC's identification requirement for artificial-voice calls ([FCC](https://docs.fcc.gov/public/attachments/FCC-24-17A1.pdf)) and NIST's question about binding agent identity to human identity both point to the same need: tying an agent to an accountable legal person, in a form someone outside the operator can check. Domain control, as in the ANS v2 draft ([IETF datatracker](https://datatracker.ietf.org/doc/draft-narajala-courtney-ansv2/)), is one proxy for that; it is evidence about a domain, not about the organization behind it.",
      ],
    },
    {
      heading: "Where AgenID sits and what it does not do yet",
      body: [
        "AgenID is an open identity and verification protocol for AI agents, published as a normative specification at [github.com/AgenID-protocol/spec](https://github.com/AgenID-protocol/spec) with an independent conformance suite under the MIT license at [github.com/AgenID-protocol/conformance](https://github.com/AgenID-protocol/conformance). Its focus is the second open problem above: letting a third party re-verify an agent's identity offline, without trusting the registry that stores it.",
        "What works today. An agent gets an identifier of the form `agenid:<ULID>`; the spec's example is `agenid:01J8Z3P2K8VW4RN7XTQ6MYD5HC`. The operator signs a ManifestProof with Ed25519 over RFC 8785 canonical JSON, binding the manifest by its SHA-256 digest. The reference registry at agenid.com resolves `https://www.agenid.com/a/<agenid>` to a Verification Card for browsers and to a canonical resolution envelope as JSON, which a verifier can re-check offline; the registry cannot forge an operator signature. Registration happens in the browser at [/issue](/issue), where the key is generated locally and never sent to AgenID, and anyone can check an agent at [/verify](/verify).",
        "Two-path key discovery is deployed on the registry side: an operator key can be fetched from `https://www.agenid.com/v1/keys/<key-ulid>` and compared with the operator's own copy at `https://<operator_domain>/.well-known/agenid/keys.json`. The second path is published by the operator. Where the operator publishes no copy, a verifier has one source, not two.",
        "The issuance ceiling. Protocol v1.1.1 defines the levels DECLARED, L1_REGISTERED, L2_DOMAIN_VERIFIED, L3_ORGANIZATION_VERIFIED and L4_DEPLOYMENT_VERIFIED; L5 is reserved and not issuable. The reference deployment at agenid.com issues nothing above L1_REGISTERED today. L2 and higher require a VerificationAssertion signed by a root authority key, and that key has not been created yet. L1 is a registration of a self-declaration; operator attestations in the manifest are self-declared and cannot be verified by anyone, including AgenID. Confirming a `_agenid` DNS TXT record at [/verify/domain](/verify/domain) records evidence of domain control and raises nothing above L1.",
        "What it does not do yet. There is no revocation flow deployed: agent status values exist in the schema, but nothing writes them, so no agent is revoked or suspended today. Retired keys stay resolvable so historical signatures remain checkable. v1.1.1 defines no signed authorization object; `permissions` and `authorizations` are reserved manifest keys, and a v1.2 authorization layer exists only as a draft in development. Nothing binds a live HTTP request to a registered agent. The partner documents for voice and agent platforms are integration patterns, not packages. In the terms of this report, AgenID addresses identity and offline re-verification; delegation, revocation and request binding remain open for AgenID as they do for the field. The [trust model](/trust) page describes these limits in more detail.",
      ],
    },
    {
      heading: "Methodology",
      body: [
        "This is a desk review, researched and written on September 23, 2026. We did not run surveys, interview vendors or test any third-party product. Each claim about a third party comes from a page we fetched on that date and is cited inline; the full list is below.",
        "Source selection followed a fixed order of preference: standards bodies and their document trackers (IETF datatracker, RFC Editor, W3C), official project specifications (A2A, MCP), regulators and legislatures (European Commission, Utah Legislature, FCC), government standards programs (NIST), peer-reviewed or arXiv papers, and then vendors' own press releases, blogs and documentation for their own products. Where only a vendor source existed, the claim is attributed to that vendor. Survey figures give the publisher, sample size and fielding dates where the source states them; forecasts are labelled as forecasts.",
        "Statuses change quickly. Internet-Drafts are revised or expire on a roughly six-month cycle, product pages are updated without notice, and the dates here reflect what each source said on the research date. We excluded claims we could not trace to a primary or first-party source, including widely repeated market-size estimates for which we found no underlying study.",
        "Corrections are welcome. If a date, status or attribution here is wrong or out of date, open an issue on the public specification repository at [github.com/AgenID-protocol/spec](https://github.com/AgenID-protocol/spec) with the source that shows the correct value, and we will update this page and its `updated` date.",
      ],
    },
  ],
  faqs: [
    {
      q: "Is there a single standard for AI agent identity in 2026?",
      a: "No. As of September 2026, request signing is converging on HTTP Message Signatures through the IETF Web Bot Auth working group, A2A defines Agent Cards for agent servers, MCP builds optional authorization on OAuth, and W3C DIDs and Verifiable Credentials are reused as general tools. They identify different things, and no single document ties them together.",
    },
    {
      q: "What is the difference between agent identity and agent authorization?",
      a: "Identity answers which agent is acting and who declared it. Authorization answers what that agent is allowed to do and on whose behalf. The sources reviewed here treat them as separate problems; NIST's 2026 concept paper, for example, lists delegation and human binding as open questions separate from identification.",
    },
    {
      q: "When does EU AI Act Article 50 apply?",
      a: "The European Commission states that the AI Act's transparency rules apply from 2 August 2026, with a grace period until December 2026 for the marking obligation on generative systems already on the market. Article 50 requires informing people that they are interacting with an AI system. This is context, not legal advice.",
    },
    {
      q: "Do payment networks identify AI agents?",
      a: "Several do, for their own networks. Mastercard Agent Pay requires agents to be registered and verified, Visa's Trusted Agent Protocol uses HTTP Message Signatures aligned with Web Bot Auth, and Google's AP2 uses signed mandates. In each case, recognition depends on the network or its partners.",
    },
    {
      q: "What level can an agent reach on AgenID today?",
      a: "The reference deployment at agenid.com issues nothing above L1_REGISTERED, which records a self-declaration. L2 and higher require a VerificationAssertion signed by a root authority key, and that key has not been created yet. L5 is reserved.",
    },
    {
      q: "How can I report an error in this report?",
      a: "Open an issue on the public AgenID specification repository on GitHub with a link to the source that shows the correct value. The report is a desk review dated September 23, 2026, and it will be updated when a correction is confirmed.",
    },
  ],
  related: [
    "/trust",
    "/how-it-works",
    "/glossary/web-bot-auth",
    "/glossary/eu-ai-act-article-50",
    "/compare/godaddy-ans",
    "/learn/how-to-verify-an-ai-agent",
  ],
  sources: [
    { label: "RFC 9421: HTTP Message Signatures (RFC Editor)", url: "https://www.rfc-editor.org/rfc/rfc9421.html" },
    { label: "IETF Web Bot Auth working group charter", url: "https://datatracker.ietf.org/wg/webbotauth/about/" },
    { label: "draft-ietf-webbotauth-httpsig-protocol (IETF datatracker)", url: "https://datatracker.ietf.org/doc/draft-ietf-webbotauth-httpsig-protocol/" },
    { label: "Cloudflare: Forget IPs, using cryptography to verify bot and agent traffic", url: "https://blog.cloudflare.com/web-bot-auth/" },
    { label: "Cloudflare: Message Signatures in the Verified Bots Program", url: "https://blog.cloudflare.com/verified-bots-with-cryptography/" },
    { label: "Cloudflare: The age of agents, signed agents", url: "https://blog.cloudflare.com/signed-agents/" },
    { label: "draft-narajala-ans (IETF datatracker)", url: "https://datatracker.ietf.org/doc/draft-narajala-ans/" },
    { label: "draft-narajala-courtney-ansv2 (IETF datatracker)", url: "https://datatracker.ietf.org/doc/draft-narajala-courtney-ansv2/" },
    { label: "W3C Decentralized Identifiers (DIDs) v1.0", url: "https://www.w3.org/TR/did-1.0/" },
    { label: "W3C Verifiable Credentials Data Model v2.0", url: "https://www.w3.org/TR/vc-data-model-2.0/" },
    { label: "A2A Protocol specification", url: "https://a2a-protocol.org/latest/specification/" },
    { label: "A2A Protocol: Agent discovery", url: "https://a2a-protocol.org/latest/topics/agent-discovery/" },
    { label: "Google Developers Blog: A2A, a new era of agent interoperability", url: "https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/" },
    { label: "Linux Foundation: Agent2Agent Protocol Project launch", url: "https://www.linuxfoundation.org/press/linux-foundation-launches-the-agent2agent-protocol-project-to-enable-secure-intelligent-communication-between-ai-agents" },
    { label: "Anthropic: Introducing the Model Context Protocol", url: "https://www.anthropic.com/news/model-context-protocol" },
    { label: "MCP specification 2026-07-28: Authorization", url: "https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization" },
    { label: "Linux Foundation: Formation of the Agentic AI Foundation", url: "https://www.linuxfoundation.org/press/linux-foundation-announces-the-formation-of-the-agentic-ai-foundation" },
    { label: "OpenID Foundation: Identity Management for Agentic AI whitepaper", url: "https://openid.net/new-whitepaper-tackles-ai-agent-identity-challenges/" },
    { label: "IETF WIMSE working group charter", url: "https://datatracker.ietf.org/wg/wimse/about/" },
    { label: "draft-oauth-ai-agents-on-behalf-of-user (IETF datatracker)", url: "https://datatracker.ietf.org/doc/draft-oauth-ai-agents-on-behalf-of-user/" },
    { label: "Microsoft Security blog: Zero Trust for the agentic workforce", url: "https://www.microsoft.com/en-us/security/blog/2025/05/19/microsoft-extends-zero-trust-to-secure-the-agentic-workforce/" },
    { label: "Microsoft Learn: What is Microsoft Entra Agent ID", url: "https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/what-is-agent-id" },
    { label: "Auth0: Announcing Auth0 for AI Agents", url: "https://auth0.com/blog/announcing-auth0-for-ai-agents-powering-the-future-of-ai-securely/" },
    { label: "GoDaddy: ANS API and Standards site", url: "https://aboutus.godaddy.net/newsroom/news-releases/press-release-details/2025/GoDaddy-advances-trusted-AI-agent-identity-with-ANS-API-and-Standards-site/default.aspx" },
    { label: "GoDaddy via PR Newswire: ANS Marketplace", url: "https://www.prnewswire.com/news-releases/godaddys-new-ans-marketplace-tells-you-which-ai-agents-you-can-trust-302646360.html" },
    { label: "Visa: Trusted Agent Protocol press release", url: "https://usa.visa.com/about-visa/newsroom/press-releases.releaseId.21716.html" },
    { label: "Mastercard: Agent Pay press release", url: "https://www.mastercard.com/us/en/news-and-trends/press/2025/april/mastercard-unveils-agent-pay-pioneering-agentic-payments-technology-to-power-commerce-in-the-age-of-ai.html" },
    { label: "Google Cloud: Announcing Agent Payments Protocol (AP2)", url: "https://cloud.google.com/blog/products/ai-machine-learning/announcing-agents-to-payments-ap2-protocol" },
    { label: "Coinbase: Introducing x402", url: "https://www.coinbase.com/developer-platform/discover/launches/x402" },
    { label: "Skyfire via Business Wire: KYAPay protocol launch", url: "https://www.businesswire.com/news/home/20250626772489/en/Skyfire-Launches-Open-KYAPay-Protocol-With-Agent-Checkout" },
    { label: "EU AI Act Article 50 text (artificialintelligenceact.eu)", url: "https://artificialintelligenceact.eu/article/50/" },
    { label: "European Commission: Quick facts, transparency rules for AI systems", url: "https://digital-strategy.ec.europa.eu/en/factpages/quick-facts-transparency-rules-ai-systems" },
    { label: "European Commission: AI Act regulatory framework", url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai" },
    { label: "Utah Legislature: S.B. 226 (2025), enrolled copy", url: "https://le.utah.gov/Session/2025/bills/enrolled/SB0226.pdf" },
    { label: "FCC 24-17 Declaratory Ruling on AI-generated voices", url: "https://docs.fcc.gov/public/attachments/FCC-24-17A1.pdf" },
    { label: "McKinsey: The state of AI in 2026", url: "https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai" },
    { label: "Gartner: 40% of enterprise apps will feature task-specific AI agents by 2026 (forecast)", url: "https://www.gartner.com/en/newsroom/press-releases/2025-08-26-gartner-predicts-40-percent-of-enterprise-apps-will-feature-task-specific-ai-agents-by-2026-up-from-less-than-5-percent-in-2025" },
    { label: "NIST CSRC: Software and AI Agent Identity and Authorization concept paper", url: "https://csrc.nist.gov/pubs/other/2026/02/05/accelerating-the-adoption-of-software-and-ai-agent/ipd" },
    { label: "NIST: AI Agent Standards Initiative", url: "https://www.nist.gov/artificial-intelligence/ai-agent-standards-initiative" },
    { label: "South et al., Authenticated Delegation and Authorized AI Agents (arXiv 2501.09674)", url: "https://arxiv.org/abs/2501.09674" },
    { label: "Chan et al., IDs for AI Systems (arXiv 2406.12137)", url: "https://arxiv.org/abs/2406.12137" },
    { label: "AgenID specification (GitHub)", url: "https://github.com/AgenID-protocol/spec" },
    { label: "AgenID conformance suite (GitHub)", url: "https://github.com/AgenID-protocol/conformance" },
  ],
  updated: "2026-09-23",
};
