import { createServer } from "node:http"; import { parse } from "node:url"; import next from "next";
import { buildApp } from "@agenid/api";
import { generateAgentId, generateKeyId, generateKeyPair, generateAssertionId, makeKeyDocument, signManifestProof, signVerificationAssertion, manifestDigestHex, ASSERTION_SCHEMA_ID } from "@agenid/core";
import { chromium } from "playwright";
const NOW="2026-09-20T00:00:00Z"; const api = buildApp({ now: () => NOW, authorityToken: "t" }); await api.listen({ port: 3901, host: "127.0.0.1" });
process.env.AGENID_API_URL="http://127.0.0.1:3901"; process.env.NEXT_PUBLIC_SITE_URL="http://127.0.0.1:3900";
const agentId=generateAgentId(); const op=generateKeyPair(); const opDoc=makeKeyDocument({keyId:generateKeyId(),publicKey:op.publicKey,role:"operator",controller:agentId,createdAt:"2026-09-01T00:00:00Z"});
const manifest={manifest_version:"1.0",agent_id:agentId,identity:{name:"Sarah",description:"Inbound appointment scheduling assistant"},ownership:{operator:"Acme Medical LLC",operator_domain:"acmemedical.com",contact:"trust@acmemedical.com"},purpose:{summary:"Schedules and reschedules patient appointments",channels:["voice","sms"]},disclosure:{is_ai:true,discloses_to_user:true,human_escalation:true}};
const proof=signManifestProof(manifest,{privateKey:op.privateKey,document:opDoc},{createdAt:"2026-09-13T00:00:00Z",expiresAt:"2026-12-12T00:00:00Z"});
await fetch("http://127.0.0.1:3901/v1/agents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({manifest,proof,key_document:opDoc})});
const au=generateKeyPair(); const auDoc=makeKeyDocument({keyId:generateKeyId(),publicKey:au.publicKey,role:"authority",controller:"agenid:authority:node-01",createdAt:"2026-09-01T00:00:00Z"});
await fetch("http://127.0.0.1:3901/v1/keys",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer t"},body:JSON.stringify(auDoc)});
const a=signVerificationAssertion({$schema:ASSERTION_SCHEMA_ID,assertion_id:generateAssertionId(),subject:agentId,subject_type:"agent",level:"L2_DOMAIN_VERIFIED",claim:{type:"domain_control",domain:"acmemedical.com"},authority:"agenid:authority:node-01",evidence:{type:"dns_txt_challenge",reference:"_agenid-challenge.acmemedical.com"},verified_at:"2026-09-13T06:00:00Z",expires_at:"2026-10-13T06:00:00Z",scope:"domain_control_only",manifest_digest:{alg:"sha-256",value:manifestDigestHex(manifest)},key_id:auDoc.key_id},{privateKey:au.privateKey,document:auDoc});
await fetch(`http://127.0.0.1:3901/v1/agents/${agentId}/assertions`,{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer t"},body:JSON.stringify({assertion:a})});
const app=next({dev:false,dir:process.cwd()}); await app.prepare(); const h=app.getRequestHandler(); const web=createServer((q,s)=>h(q,s,parse(q.url,true))); await new Promise(r=>web.listen(3900,"127.0.0.1",r));
const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1280,height:900}});
await p.goto(`http://127.0.0.1:3900/a/${agentId}`); await p.waitForTimeout(500); await p.screenshot({path:"/tmp/card.png",fullPage:true});
await p.goto("http://127.0.0.1:3900/"); await p.waitForTimeout(2500); await p.screenshot({path:"/tmp/home.png",fullPage:true});
await b.close(); web.close(); await api.close(); await app.close(); process.exit(0);
